### PR TITLE
Added eslint + standard config

### PR DESCRIPTION
**Pull request by bali182**
But it's currently commented out in `.travis.yml` since we have a few issues and I didn't want to perform the surgery

### CODE REVIEW

**Comment by bali182** [comment]
Errors were small, fixed them anyways

**Comment by sdgluck** [comment]
Looks good! I guess we should add `npm run lint` before the build step in the `prepublishOnly` script.

**Comment by bali182** [comment]
Done ☑️

**Comment by sdgluck** [comment]
Awesome - thanks!

**Pull request merged**
